### ISSUE TITLE
Could not use the library in K6 project

### ISSUE THREAD

**Issue by eduardlavrov** [QANSIGLIERE/RandomDataGenerators#5]
Hi.

When I import the library into any k6 project and run tests, I get this error::
`GoError: The moduleSpecifier "qansigliere-randomdatagenerators" couldn't be recognised as something k6 supports.
        at go.k6.io/k6/js.(*requireImpl).require-fm (native)`

**Comment by QANSIGLIERE** [comment]
This is specific of K6. To solve the problem You just need to change import in Your tests:
`import {
  randomInteger,
  randomFloat,
  randomIntegerBetweenMinMax,
  randomArrayItem,
  randomBoolean,
  randomString,
  randomPhoneNumber,
  randomEmail,
  randomIP,
  randomStringFromTemplate,
  randomTimeZone,
  randomCurrency,
  randomEmoji,
  randomColor,
  randomCarType,
  randomCarBrand,
} from "https://raw.githubusercontent.com/QANSIGLIERE/RandomDataGenerators/v0.3.0/lib/randomDataGenerators.js";`
^ this should fix the problem
